#Name of the application
spring:
  application:
    name: ZuulService

#Eureka server url for registering
#This is eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
#register url to server    

instance:
  hostname: localhost
  
server:
  port: 8989
  
zuul:
  prefix: /banking
  routes:
#    userAccessService:
#      path: /userservice/**
#      service-id: USERACCESSSERVICE
#    trainingsService:
#      path: /trainingsService/**
#      service-id: TRAININGSSERVICE
    bankingService:
      path: /bankingService/**
      service-id: BANKINGSERVICE
      
    transactionService:
      path: /transactionService/**
      service-id: TRANSACTIONSERVICE
    loanService:
      path: /loanService/**
      service-id: LOANSERVICE  
#    mentorSkillCalendarService:
#      path: /skillMentService/**
#      service-id: MENTORSKILLCALENDARSERVICE
#    paymentsService:
#      path: /paymentService/**
#      service-id: PAYMENTSSERVICE

     
     
      